"""initial tables

Revision ID: d64f77867060
Revises: 
Create Date: 2025-11-22 18:11:07.808244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd64f77867060'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rma_kg', sa.Float(), nullable=False),
    sa.Column('rma_vaten', sa.Integer(), nullable=False),
    sa.Column('kost_vaten', sa.Float(), nullable=False),
    sa.Column('inhoud_vat', sa.Float(), nullable=False),
    sa.Column('kost_ophaling', sa.Float(), nullable=False),
    sa.Column('kost_verwerking', sa.Float(), nullable=False),
    sa.Column('paritair', sa.String(length=50), nullable=False),
    sa.Column('werkdagen', sa.Integer(), nullable=False),
    sa.Column('recommended_machine', sa.String(length=80), nullable=True),
    sa.Column('new_cost', sa.Float(), nullable=True),
    sa.Column('payback', sa.Float(), nullable=True),
    sa.Column('dcf', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('calculation')
    # ### end Alembic commands ###
